name: 'Service Test'
description: Execute Postman collections using Newman
inputs:
    collection:
        description: 'Postman collection'
        required: true
        default: './tests/postman-collection.json'
    environment:
        description: 'Postman environment variables'
        required: false
        default: ''
outputs:
    result:
        description: "Test result"
runs:
  using: 'docker'
  image: 'Dockerfile'
