name: 'Service Test'
description: Execute Postman collections using Newman
inputs:
    collectionPath:
        description: 'Postman collection'
        required: true
        default: './tests/postman-collection.json'
    environmentPath:
        description: 'Postman environment variables'
        required: false
        default: ''
outputs:
    testReportPath:
        description: "Path to the generated HTML Test Resport"
runs:
  using: 'docker'
  image: 'Dockerfile'
